language: r
r: bioc-devel
warnings_are_errors: false
cache: packages
r_build_args: "--no-manual --no-resave-data"
r_check_args: "--no-build-vignettes --no-manual --timings"
before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
notifications:
  slack:
    secure: DVJqlUS+Qfxl0xQseproJxaT0NpcBL0QxxADBzM2gaPIA6gLrdNZ+ELOW7Itc+1dAKzaRA+59+HKEt24OOg+2E1bRM9z+cUz0H6xy6QzqoMUf0XVBqFxtqPKewyKtO83cgoKoQcmctzSX8/0gFh83qG/GWaz/wOdew/y2F70jezK7R0a3ifP82aIo184vkrYx1NWuh6ctsDfifN5ZFAjBhJaMEgS4oUdthE6AVsowp7Dj6kMwU7C5fQ89ka0eq2HSJhgtKqdsLx9AsemWUorH1B0Xesnbu3GTPcy0PSn8VWTzMAUJy8Cr9r6h+0tGMyXAt9gN4w8RRpXvejr7QaIoDVlUIqjtV3Y3caCS7chKlVF6Pl+SZjMfGu2oPEj2n11a0+YJcx0/FJTDQ26ecOMxsxwhRSg/pMls2KN9jmtVfC5fif/2ZWFN5kPsdGsZm4HiCV9FixlifbvHUzqx+jaZerFJKSgngE7Qb9cb6KA6jTfsdJo2IC0X2Dq/ukxrElR58H7rcDmelPbbEbyFvyH6sSWWB6FW+gHCAbKWOZ/cGP+nbUBsDjn4LgejVXLRq3eO8SlGa4nJtI76/J1uMOD+OlYos3rMbvHQnq741nCkOGn60sYVHKAOm84mljhT/il3T+J3iJHdp32vl/ZlDGFlsqCpK/E2hfQNTPk4mZsoZY=
